import Head from 'next/head'
import { Flex, Text, Button, Image, Heading, Input, InputGroup, InputRightElement } from '@chakra-ui/react'
import { useSession, signIn, signOut } from 'next-auth/react'

export default function Home() {
  const { data: session } = useSession()
  console.log(session)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex bgImage='url(/chart2.png)' bgRepeat='none' bgSize='cover' bgColor='black' h='100vh' w='100%' direction='column' align='center'>
        <Flex w='50%' h='8vh' align='center' justify='space-between'>
          <Image src='/apexlogo.png' boxSize={10} />
          { !session ? <Button onClick={() => signIn('discord')} bgColor='#5865f2' leftIcon={<Image src='/discord.png' boxSize={5}/>}>Sign In</Button> : <Button onClick={() => signOut()}>{session.user.name}</Button> }
        </Flex>
        <Flex h='76vh' direction='column' align='center' justify='center'>
          <Heading fontSize='500%'>Welcome to Apex</Heading>
          <InputGroup mt='5%'>
            <Input pr='4.5rem' placeholder='TradingView Username'></Input>
            <InputRightElement w='4.5rem'>
              <Button borderRadius='0px 5px 5px 0px' fontSize='75%'>Submit</Button>
            </InputRightElement>
          </InputGroup>
        </Flex>
      </Flex>
    </>
  )
}
